spring:
  application:
    name: basic-rest-api

  messages:
    basename: i18n/messages

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #default_batch_fetch_size: 100

  devtools:
    livereload.enabled: true
    restart.enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    io.devfactory: debug
    org.hibernate.SQL: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
