###
// users 목록 조회
GET http://localhost:8080/users

###
// user 1  조회
GET http://localhost:8080/users/2

###
// user 저장
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "dev4",
  "joinDate": "2020-06-11T23:28:26.9327792"
}

> {%
  client.global.set("userId", response.body.id)
%}

###
// 저장한 user 조회
GET http://localhost:8080/users/{{userId}}
