###
// jpa users 목록 조회
GET http://localhost:8080/jpa/users
Authorization: Basic {{username}} {{password}}

###
// jpa users 1 조회
GET http://localhost:8080/jpa/users/1
Authorization: Basic {{username}} {{password}}

###
// user 저장
POST http://localhost:8080/jpa/users
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "name": "dev4",
  "joinDate": "2020-06-11T23:28:26",
  "password": "1234",
  "ssn": "12345-67890"
}

> {%
  client.global.set("location", response.headers.valueOf('Location'))
%}

###
// 저장한 user 조회
GET {{location}}
Authorization: Basic {{username}} {{password}}

###
// user 1 삭제
DELETE http://localhost:8080/jpa/users/1
Authorization: Basic {{username}} {{password}}

###
// user 1 의 post 목록 조회
GET http://localhost:8080/jpa/users/1/posts
Authorization: Basic {{username}} {{password}}

###
// user 1 의 post 등록
POST http://localhost:8080/jpa/users/1/posts
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "description": "post 5"
}

> {%
  client.global.set("location", response.headers.valueOf('Location'))
%}
